/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { IERC20 } from "./@openzeppelin/contracts/token/ERC20/IERC20";
export { IERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/IERC20__factory";
export type { DividendDistributor } from "./contracts/DividendDistributor";
export { DividendDistributor__factory } from "./factories/contracts/DividendDistributor__factory";
export type { PropertySale } from "./contracts/PropertySale";
export { PropertySale__factory } from "./factories/contracts/PropertySale__factory";
